import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// ** Components
import FlowLineBackground from "@/components/effects/flow-line-background";

// ** Context
import ThemeContext from "@/context/theme-context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ngô Minh Khôi - Frontend Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <main className="pb-8">
          <ThemeContext>
            <FlowLineBackground />
            {children}
          </ThemeContext>
        </main>
      </body>
    </html>
  );
}
